# Accuracy across 1 runs: 0.796911
version: 0.0.1
pipeline_name: nodepred-ns
device: cuda
eval_device: cpu
data:
  name: ogbn-products
  split_ratio:                # Ratio to generate split masks, for example set to [0.8, 0.1, 0.1] for 80% train/10% val/10% test. Leave blank to use builtin split in original dataset
model:
  name: sage
  embed_size: -1              # The dimension of created embedding table. -1 means using original node embedding
  hidden_size: 256             # Hidden size.
  num_layers: 3               # Number of hidden layers.
  activation: relu
  dropout: 0.5                # Dropout rate.
  aggregator_type: gcn        # Aggregator type to use (``mean``, ``gcn``, ``pool``, ``lstm``).
general_pipeline:
  sampler:
    name: neighbor
    fan_out:
    - 5
    - 10
    - 15
    batch_size: 1000
    num_workers: 4
    eval_batch_size: 10000
    eval_num_workers: 4
  early_stop:
    patience: 20              # Steps before early stop
    checkpoint_path: checkpoint.pth # Early stop checkpoint model file path
  num_epochs: 20             # Number of training epochs
  eval_period: 5              # Interval epochs between evaluations
  optimizer:
    name: Adam
    lr: 0.005
    weight_decay: 0.0
  loss: CrossEntropyLoss
  save_path: "model.pth"
  num_runs: 5                 # Number of experiments to run
