# Accuracy across 5 runs: 0.593288 ± 0.006103
version: 0.0.1
pipeline_name: nodepred-ns
device: 'cuda:0'
eval_device: 'cpu'
data:
  name: ogbn-arxiv
model:
  name: gcn
  embed_size: -1              # The dimension of created embedding table. -1 means using original node embedding
  hidden_size: 256             # Hidden size.
  num_layers: 2               # Number of layers.
  norm: both                  # GCN normalization type. Can be 'both', 'right', 'left', 'none'.
  activation: relu            # Activation function.
  dropout: 0.5                # Dropout rate.
  use_edge_weight: false      # If true, scale the messages by edge weights.
general_pipeline:
  sampler:
    name: neighbor
    fan_out:
    - 5
    - 10
    batch_size: 1024
    num_workers: 4
    eval_batch_size: 10240
    eval_num_workers: 4
  num_epochs: 20              # Number of training epochs
  eval_period: 1              # Interval epochs between evaluations
  optimizer:
    name: Adam
    lr: 0.005
    weight_decay: 0.0
  loss: CrossEntropyLoss
  save_path: "model.pth"
  num_runs: 5
