apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: dgl-ci-gpu-compile
    image: dgllib/dgl-ci-gpu:cu101_v220123
    imagePullPolicy: Always
    tty: true
    resources:
      requests:
        cpu: 32
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: beta.kubernetes.io/instance-type
  #           operator: In
  #           values:
  #           - c5.9xlarge