apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: dgl-ci-lint
    image: dgllib/dgl-ci-lint
    imagePullPolicy: Always
    tty: true
    resources:
      requests:
        cpu: 1
  serviceAccountName: dglciuser